tc_d8_web:
    image: touchcast/docker-nginx-php7
    ports:
        - "80:80"
    volumes:
        - ./webroot:/var/www/html
    links:
     - tc_d8_db:tc_d8_db_container
tc_d8_db:
    image: mysql
    ports:
        - "3306"
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: project_db
